services:
  single_page:
    build: .
    container_name: single_page
    ports:
      - "3000:80"
    environment:
      - ./.env
    networks:
        - proxy


networks:
  proxy:
    external: true
